export enum InventoryItemsEnum {
  GOLD_PICKAXE_ITEM = "GOLD_PICKAXE_ITEM",
  IRON_PICKAXE_ITEM = "IRON_PICKAXE_ITEM",
  COPPER_PICKAXE_ITEM = "COPPER_PICKAXE_ITEM",
  STONE_PICKAXE_ITEM = "STONE_PICKAXE_ITEM",
  WOOD_PICKAXE_ITEM = "WOOD_PICKAXE_ITEM",

  GOLD_SWORD_ITEM = "GOLD_SWORD_ITEM",
  IRON_SWORD_ITEM = "IRON_SWORD_ITEM",
  COPPER_SWORD_ITEM = "COPPER_SWORD_ITEM",
  STONE_SWORD_ITEM = "STONE_SWORD_ITEM",
  WOOD_SWORD_ITEM = "WOOD_SWORD_ITEM",

  GOLD_HELMET_ITEM = "GOLD_HELMET_ITEM",
  IRON_HELMET_ITEM = "IRON_HELMET_ITEM",
  COPPER_HELMET_ITEM = "COPPER_HELMET_ITEM",
  STONE_HELMET_ITEM = "STONE_HELMET_ITEM",
  WOOD_HELMET_ITEM = "WOOD_HELMET_ITEM",

  GOLD = "GOLD",
  IRON = "IRON",
  COPPER = "COPPER",
  STONE = "STONE",
  WOOD = "WOOD",

  BERRY = "BERRY",
  APPLE = "APPLE"
}
