export const Assets = Object.freeze([
  { name: "Apple Tree", id: "AppleTree", asset: "apple-tree.png" },
  { name: "Apple", id: "Apple", asset: "apple.png" },
  { name: "Berry", id: "Berry", asset: "berry.png" },
  { name: "Bush", id: "Bush", asset: "bush.png" },
  { name: "Lake", id: "Lake", asset: "lake.png" },
  { name: "Large Copper Ore", id: "LargeCopperOre", asset: "large-copper-ore.png" },
  {
    name: "Large Dark Oak Tree",
    id: "LargeDarkOakTree",
    asset: "large-dark-oak-tree.png",
  },
  { name: "Large Gold Ore", id: "LargeGoldOre", asset: "large-gold-ore.png" },
  { name: "Large Hill", id: "LargeHill", asset: "large-hill.png" },
  { name: "Large Iron Ore", id: "LargeIronOre", asset: "large-iron-ore.png" },
  { name: "Large Oak Tree", id: "LargeOakTree", asset: "large-oak-tree.png" },
  {
    name: "Large Pink Flower",
    id: "LargePinkFlower",
    asset: "large-pink-flower.png",
  },
  { name: "Large Rock", id: "LargeRock", asset: "large-rock.png" },
  {
    name: "Large White Flower",
    id: "LargeWhiteFlower",
    asset: "large-white-flower.png",
  },
  {
    name: "Medium Dark Oak Tree",
    id: "MediumDarkOakTree",
    asset: "medium-dark-oak-tree.png",
  },
  { name: "Medium Oak Tree", id: "MediumOakTree", asset: "medium-oak-tree.png" },
  { name: "Pebble", id: "Pebble", asset: "pebble.png" },
  { name: "Small Copper Ore", id: "SmallCopperOre", asset: "small-copper-ore.png" },
  {
    name: "Small Dark Oak Tree",
    id: "SmallDarkOakTree",
    asset: "small-dark-oak-tree.png",
  },
  { name: "Small Gold Ore", id: "SmallGoldOre", asset: "small-gold-ore.png" },
  {
    name: "Small Green Flower",
    id: "SmallGreenFlower",
    asset: "small-green-flower.png",
  },
  { name: "Small Hill", id: "SmallHill", asset: "small-hill.png" },
  { name: "Small Iron Ore", id: "SmallIronOre", asset: "small-iron-ore.png" },
  { name: "Small Oak Tree", id: "SmallOakTree", asset: "small-oak-tree.png" },
  {
    name: "Small Pink Flower",
    id: "SmallPinkFlower",
    asset: "small-pink-flower.png",
  },
  { name: "Small Rock", id: "SmallRock", asset: "small-rock.png" },
  {
    name: "Small White Flower",
    id: "SmallWhiteFlower",
    asset: "small-white-flower.png",
  },
  { name: "Stone Path", id: "StonePath", asset: "stone-path.png" },
  { name: "Wilder Left Arm", id: "WilderLeftArm", asset: "wilder-left-arm.png" },
  { name: "Wilder Right Arm", id: "WilderRightArm", asset: "wilder-right-arm.png" },
  { name: "Wilder", id: "Wilder", asset: "wilder.png" },
])
