export const SpriteRenderingOrder = Object.freeze([
  "SMALL_HILL",
  "LARGE_HILL",
  "STONE_PATH",
  "LAKE",

  "PEBBLE",
  "SMALL_GREEN_FLOWER",
  "SMALL_PINK_FLOWER",
  "SMALL_WHITE_FLOWER",
  "LARGE_PINK_FLOWER",
  "LARGE_WHITE_FLOWER",

  "BUSH",
  "BERRY",

  "SMALL_ROCK",
  "SMALL_COPPER_ORE",
  "SMALL_IRON_ORE",
  "SMALL_GOLD_ORE",

  "LARGE_ROCK",
  "LARGE_COPPER_ORE",
  "LARGE_IRON_ORE",
  "LARGE_GOLD_ORE",

  "WILDER_ARM_ITEM",
  "WILDER_ARM",
  "WILDER",
  "WILDER_USERNAME",

  "APPLE_TREE",
  "APPLE",

  "SMALL_DARK_OAK_TREE",
  "SMALL_OAK_TREE",

  "MEDIUM_DARK_OAK_TREE",
  "MEDIUM_OAK_TREE",

  "LARGE_DARK_OAK_TREE",
  "LARGE_OAK_TREE",

  "INVENTORY",
  "STATS",
  "WOOD"
]);
